name: 构建成品

# 触发条件：在 push 到 master 分支后
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10

# 任务
jobs:
  build-and-release:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 准备 Golang 环境
        uses: actions/setup-go@v2.1.2

      - name: 编译成品
        run: go build -o package/image-syncer ./main.go

      - name: 创建 Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # body:
          draft: false
          prerelease: false

      - name: 向 Release 添加文件
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: package/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
